name: Build & Push rag-chat-ui

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env files
        run: |
          echo "${{ vars['Environment variables'] || secrets['Environment variables'] }}" > .env
          cp .env backend/.env
          cp .env frontend/.env
          cp .env admin-frontend/.env

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build & push
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/rag-chat-backend:latest ./backend
          docker push ghcr.io/${{ github.repository_owner }}/rag-chat-backend:latest
          docker build -t ghcr.io/${{ github.repository_owner }}/rag-chat-frontend:latest ./frontend
          docker push ghcr.io/${{ github.repository_owner }}/rag-chat-frontend:latest
          docker build -t ghcr.io/${{ github.repository_owner }}/rag-chat-admin:latest ./admin-frontend
          docker push ghcr.io/${{ github.repository_owner }}/rag-chat-admin:latest
